### ISSUE TITLE
Imperial Commander's Armoury doesn't quite work for command squad models yet

### ISSUE THREAD

**Issue by TheHalfinStream** [TheHalfinStream/Astra-Militarum-9th-Battlescribe-MG-COMMUNITY-ver-unofficial-#24]

**Comment by 3Komnenos3** [comment]
![image](https://user-images.githubusercontent.com/118828186/205524336-4900145e-6bbf-4a3f-91e6-df43f2afb257.png)

Changed the implementation of this and while a little clunky, it seems to enable command squad models to take heirlooms.
